### ISSUE TITLE
Root words database

### ISSUE THREAD

**Issue by osamaramihafez** [Quran-Journey/roots#12]
We want to structure a database such that each of the ayat is connected to all of its root words. We will be using the SQL dump found through [the Tanzil docs](https://tanzil.net/download/). This SQL dump contains all of the verses of the Quran. Our priority should be structuring the relationships in a way that makes it easy to attack all of the root words for a verse to the verse itself.

**Comment by osamaramihafez** [comment]
The current objective is to insert the root words (along with transliteration) into the database

**Comment by Tahir001** [comment]
Since the Arabic text output does not come out the correct way in terminal, we will be using a jupyter notebook (.ipynb file) to develop the script and copy the final version over to the insert_data.py file
