### ISSUE TITLE
Display bug on ظلم root

### ISSUE THREAD

**Issue by Baraw** [Quran-Journey/roots#58]
![Screenshot_20230623_184952_Chrome](https://github.com/Quran-Journey/roots/assets/7683668/ea7604d7-9982-4835-b01e-dde41619ab44)

They are numbers displayed and more stuffs.

**Comment by osamaramihafez** [comment]
We are planning to clean up and replace much of the data as most of it is not clean enough for production.

This tool was mostly a test tool at the moment.
